### ISSUE TITLE
k8s_status doesn't work when using lists

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk-ansible-util#12]
Assume `current_cr` is a fact that contains the current CR being processed.

```
- operator_sdk.util.k8s_status:
    api_version: "{{ current_cr.apiVersion }}"
    kind: "{{ current_cr.kind }}"
    name: "{{ current_cr.metadata.name }}"
    namespace: "{{ current_cr.metadata.namespace }}"
    status:
      foo: ["one", "two"]

- operator_sdk.util.k8s_status:
    api_version: "{{ current_cr.apiVersion }}"
    kind: "{{ current_cr.kind }}"
    name: "{{ current_cr.metadata.name }}"
    namespace: "{{ current_cr.metadata.namespace }}"
    status:
      foo: ["two"]
```

Results in the status.foo field containing both "one" and "two" rather than just "two" (which it should be):

```
status:
  conditions:
  - ansibleResult:
      changed: 17
    ...and the rest...
    message: Awaiting next reconciliation
  foo:
  - one
  - two
```

cc @fabianvf
