### ISSUE TITLE
ansible dictionary conversion replaces dash "-" with underscore "_"

### ISSUE THREAD

**Issue by mihaics** [operator-framework/operator-sdk-ansible-util#16]
I have an ansible role (using ansible operator), which uses a dictionary to loop thru variables:

```
volumes:
  customapps-storage: 1G
  config-storage: 1G
  userdata-storage: 2G
  webdata-storage: 1G
 ```
this are defined in role defaults/main.yml

They are decoded like this: 
 `loop: "{{ volumes | dict2items(key_name='volume', value_name='size')}}"`
 
 all ok, (item.volume = config-storage) but when I create the manifest, 
 
```
 apiVersion: storage.cloud/v1
kind: CloudStorage
metadata:
  name: cloudstorage
  namespace: cloud
spec:
  volumes:
    customapps-storage: 1G
    config-storage: 1G
    userdata-storage: 2G
    webdata-storage: 1G
```

 this variables are decoded as config_storage, userdata_storage etc, replacing "-" with "_". 
(item.volume = config_storage)
(tested thoroughly )

Of course, may be an ansible python/jinja issue only and it manifests as side effect in operator, but it works from defaults and not from deployment file.
   

To be clear, when I run with an empty manifest, like this, the values taken from defaults are correct:

 
```
 apiVersion: storage.cloud/v1
kind: CloudStorage
metadata:
  name: cloudstorage
  namespace: cloud
spec:
```

any value with dash in dictionary, is converted to underscore. If I dont use dashes, all works ok.
