### ISSUE TITLE
Add k8s_event module to collection

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk-ansible-util#2]
##### SUMMARY

A `k8s_event` module would be nice to have in certain circumstances. If you want to be able to add events attached to certain resources, this module could help you do that.

See: https://github.com/operator-framework/operator-metering/blob/master/images/metering-ansible-operator/roles/meteringconfig/library/k8s_event.py

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

Example task:

```yaml
- name: Create Kubernetes Event
  k8s_event:
    state: present
    name: test-https-emily109
    namespace: default
    message: Event created
    reason: Created
    reportingComponent: Reporting components
    type: Normal
    source:
      component: Metering components
    involvedObject:
      apiVersion: v1
      kind: Service
      name: test-https-emily107
      namespace: default
```

Note: This was migrated from https://github.com/ansible-collections/kubernetes/issues/8
