### ISSUE TITLE
k8s_status converting ints to strings inside the status dict.

### ISSUE THREAD

**Issue by Freyert** [operator-framework/operator-sdk-ansible-util#9]
I have status fields in my custom resource definition that I would like to enforce as integers, but it seems that the k8s_status module is converting them to strings even when I coerce to int.

```
- name: update number of provisioned instances
  operator_sdk.util.k8s_status:
    api_version: "{{ crd.group }}"
    kind: "{{ crd.kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      provisionedInstances: "{{ groups['x'] | length | int }}" # <- should be int
```

When the module runs I get this error:

```
{
  "reason":"FieldValueInvalid",
  "message":"Invalid value: \\\\"string\\\\": status.provisionedInstances in body must be of type 
   integer: \\\\"string\\\\"","field":"status.provisionedInstances"
}]},"code":422}
```

The CRD definition would look something like this:
```
....
        status:
          properties:
            provisionedInstances:
              type: integer
...
```

Version Info:
* ansible-playbook 2.9.9

**Comment by fabianvf** [comment]
I think to get this to work you need to enable jinja2 native types (see https://docs.ansible.com/ansible/latest/reference_appendices/config.html#envvar-ANSIBLE_JINJA2_NATIVE)

Alternatively/if that doesn't work, I think you may have to move the value you would like to be a non-string into a template and load it from there (with the `template` lookup plugin), the issue is that the quotes around the value make ansible receive it as a string regardless of what the value enclosed in quotes is. Obviously removing the quotes doesn't work because that causes syntax errors, so you would probably want to create a template for your status that looks like:

```
provisionedInstances: {{ groups['x'] | length | int }}
```

(note the lack of quotes)

and then your task would look like

```yaml
- name: update number of provisioned instances
  operator_sdk.util.k8s_status:
    api_version: "{{ crd.group }}"
    kind: "{{ crd.kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status: "{{ lookup('template', status_template) | from_yaml }}'
```
